
all: open_logfile.o close_logfile.o write_logfile.o now.o

open_logfile.o: open_logfile.c
	gcc -g -c open_logfile.c

close_logfile.o: close_logfile.c
	gcc -g -c close_logfile.c

write_logfile.o: write_logfile.c
	gcc -g -c write_logfile.c

now.o: now.c
	gcc -g -c now.c
