
another_gethostent: another_gethostent.o
	gcc -o another_gethostent another_gethostent.o

another_gethostent.o:  another_gethostent.c
	 gcc -g -c another_gethostent.c

test_gethostent: test_gethostent.o
	gcc -o test_gethostent test_gethostent.o

test_gethostent.o:  test_gethostent.c
	 gcc -g -c test_gethostent.c

test2: test2.o
	gcc -o test2 test2.o

test2.o:  test2.c
	 gcc -g -c test2.c

test: test.o
	gcc -o test test.o

test.o:  test.c
	 gcc -g -c test.c

