
dave: open_log_file.o close_logfile.o write_logfile.o now.o build_server.o test.o
	gcc -o dave open_log_file.o close_logfile.o write_logfile.o now.o build_server.o test.o

open_log_file.o: open_log_file.c
	gcc -g -c open_log_file.c

close_logfile.o: close_logfile.c
	gcc -g -c close_logfile.c

write_logfile.o: write_logfile.c
	gcc -g -c write_logfile.c

now.o: now.c
	gcc -g -c now.c

build_server.o: build_server.c
	gcc -g -c build_server.c

test.o: test.c
	gcc -g -c test.c
